# Generated by Django 4.1.5 on 2023-03-04 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/articulos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ultima_compra',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 22, 2, 8, 681042)),
        ),
    ]
