# Generated by Django 4.1.5 on 2023-03-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('embutidos', 'Embutidos'), ('juegos', 'Juegos'), ('juguetes', 'Juguetes'), ('almacen', 'Almacén'), ('golosinas', 'Golosinas'), ('limpieza', 'Limpieza'), ('congelados', 'Congelados'), ('desayuno', 'Desayuno'), ('panaderia', 'Panadería'), ('tabaco', 'Tabaco'), ('revistas', 'Revistas'), ('deportes', 'Deportes'), ('otro', 'Otro')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
