# Generated by Django 4.1.5 on 2023-03-04 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_articulo_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_subida',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 22, 34, 12, 988051)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ultima_compra',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 22, 34, 12, 989051)),
        ),
    ]
