# Generated by Django 4.1.5 on 2023-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_articulo_categoria_articulo_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categorias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
